name: Build Python

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
jobs:
  build-windows:
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.7

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: build with pyinstaller
      run: |
        pyinstaller -F main.py
        
    - name: Rename Windows
      run: |
        cd dist
        mv main.exe HSVN-Windows-tool.exe
        
    - name: upload to release 
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/HSVN-Windows-tool.exe
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
  
  build-macos:
    runs-on: macos-latest
    steps: 
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.7

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: build with pyinstaller
      run: |
        pyinstaller -F main.py
        
    - name: Rename MacOS
      run: |
        cd dist
        mv main HSVN-MacOS-tool

    - name: upload to release 
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/HSVN-MacOS-tool
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  build-linux:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9.7

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: build with pyinstaller
      run: |
        pyinstaller -F main.py
        
    - name: Rename Linux
      run: |
        cd dist
        mv main HSVN-Linux-tool

    - name: upload to release 
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/HSVN-Linux-tool
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
