
name: Package Application with Pyinstaller

on:
  push:
    tags:
       - 'v*'

jobs:
  build:
    # Build for Windows, Linux and MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --onefile main.py
      - name: change name for windows
        if: matrix.os == 'windows-latest'
        run: |
          mv dist/main.exe dist/HSVN-Tools.exe
      - name: change name for macos
        if: matrix.os == 'macos-latest'
        run: |
          mv dist/main dist/HSVN-Tools
      - name: change name for linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/main dist/HSVN-Tools
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HSVN-Tools-${{ matrix.os }}
          path: dist/
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          file_glob: true