
name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Build for Windows, Linux and MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --onefile main.py
      - name: change name for windows
        if: matrix.os == 'windows-latest'
        run: |
          mv dist/main.exe dist/main.exe
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: dist/main